In [1]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.datasets import load_iris





In [2]:
d=load_iris()

In [3]:
d1=pd.DataFrame(d.data)

In [4]:
d1['Species']=d.target

In [44]:
d1

0    1    2    3  Species
0    5.1  3.5  1.4  0.2        0
1    4.9  3.0  1.4  0.2        0
2    4.7  3.2  1.3  0.2        0
3    4.6  3.1  1.5  0.2        0
4    5.0  3.6  1.4  0.2        0
..   ...  ...  ...  ...      ...
145  6.7  3.0  5.2  2.3        2
146  6.3  2.5  5.0  1.9        2
147  6.5  3.0  5.2  2.0        2
148  6.2  3.4  5.4  2.3        2
149  5.9  3.0  5.1  1.8        2

[150 rows x 5 columns]

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
xtrain,xtest,ytrain,ytest=train_test_split(d.data,d.target,test_size=.3)

In [7]:
sv=SVC(C=20,gamma='auto',kernel='linear')
sv.fit(xtrain,ytrain)
sv.score(xtest,ytest)

0.9777777777777777

In [50]:
sv.get_params()

{'C': 10,
 'break_ties': False,
 'cache_size': 200,
 'class_weight': None,
 'coef0': 0.0,
 'decision_function_shape': 'ovr',
 'degree': 3,
 'gamma': 'auto',
 'kernel': 'linear',
 'max_iter': -1,
 'probability': False,
 'random_state': None,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

In [9]:
from sklearn.model_selection import cross_val_score

In [27]:
cross_val_score(SVC(C=10,gamma='auto',kernel='linear'),d.data,d.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [28]:
cross_val_score(SVC(C=10,gamma='auto',kernel='rbf'),d.data,d.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [30]:
cross_val_score(SVC(C=20,gamma='auto',kernel='linear'),d.data,d.target,cv=5)

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

In [10]:
kernal=['rbf','linear']
c=[1,10,20]
avgscore={}
for i in kernal:
    for j in c:
        cvscore=cross_val_score(SVC(C=j,gamma='auto',kernel=i),d.data,d.target,cv=5)
        avgscore[i,j]=np.average(cvscore)

avgscore
    
    
    

{('rbf', 1): 0.9800000000000001,
 ('rbf', 10): 0.9800000000000001,
 ('rbf', 20): 0.9666666666666668,
 ('linear', 1): 0.9800000000000001,
 ('linear', 10): 0.9733333333333334,
 ('linear', 20): 0.9666666666666666}

In [8]:
from sklearn.model_selection import GridSearchCV
clf=GridSearchCV(SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5)

clf.fit(d.data,d.target)
clf.cv_results_



{'mean_fit_time': array([0.00390291, 0.00150032, 0.01371617, 0.00192928, 0.00340805,
        0.00263906]),
 'std_fit_time': array([0.00142207, 0.00050461, 0.02007904, 0.00077363, 0.00120389,
        0.00123827]),
 'mean_score_time': array([0.00369735, 0.00159097, 0.001932  , 0.0017302 , 0.01039987,
        0.00128307]),
 'std_score_time': array([0.00388087, 0.00095774, 0.00043865, 0.00025601, 0.01422271,
        0.00040786]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],


In [54]:
dir(clf)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 '_validate_params',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 '

In [9]:
o=pd.DataFrame(clf.cv_results_)
o

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.003903      0.001422         0.003697        0.003881       1   
1       0.001500      0.000505         0.001591        0.000958       1   
2       0.013716      0.020079         0.001932        0.000439      10   
3       0.001929      0.000774         0.001730        0.000256      10   
4       0.003408      0.001204         0.010400        0.014223      20   
5       0.002639      0.001238         0.001283        0.000408      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [12]:
p=o[['param_C','param_kernel','mean_test_score']]

In [13]:
p

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [63]:
clf.best_score_

0.9800000000000001

In [69]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [78]:
from sklearn.model_selection import RandomizedSearchCV
clf=RandomizedSearchCV(SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5,n_iter=2)

clf.fit(d.data,d.target)
clf.cv_results_



{'mean_fit_time': array([0.00216417, 0.00121298]),
 'std_fit_time': array([0.0009487 , 0.00039437]),
 'mean_score_time': array([0.00166306, 0.00100613]),
 'std_score_time': array([1.11229065e-03, 1.13473218e-05]),
 'param_kernel': masked_array(data=['linear', 'linear'],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'param_C': masked_array(data=[10, 1],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'params': [{'kernel': 'linear', 'C': 10}, {'kernel': 'linear', 'C': 1}],
 'split0_test_score': array([1.        , 0.96666667]),
 'split1_test_score': array([1., 1.]),
 'split2_test_score': array([0.9       , 0.96666667]),
 'split3_test_score': array([0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1.]),
 'mean_test_score': array([0.97333333, 0.98      ]),
 'std_test_score': array([0.03887301, 0.01632993]),
 'rank_test_score': array([2, 1])}

In [79]:
dr=pd.DataFrame(clf.cv_results_)

In [80]:
dr[['param_kernel','param_C','mean_test_score']]

param_kernel param_C  mean_test_score
0       linear      10         0.973333
1       linear       1         0.980000