In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [2]:
d=load_digits()

In [3]:
dir(d)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [4]:
d.data.shape

(1797, 64)

In [5]:
d.target.shape


(1797,)

In [6]:
p=pd.DataFrame(d.data)
p

0    1     2     3     4     5    6    7    8    9   ...   54   55  \
0     0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  4.0  0.0   
1793  0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  1.0  0.0   
1794  0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  2.0  0.0   
1796  0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  8.0  0.0   

       56   57   58    59    60    61   62   63  
0     0.0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1     0.0  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2     0.0  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3     0.0  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4     0.0  0.0  0.0   2.0  16.0   4.0  0.0  0.0  
...   ...  ...  ...   ...   ...   ...  ...  ...  
1792  0.0  0.0  2.0  14.0  15.0   9.0  0.0  0.0  
1793  0.0  0.0  6.0  16.0  14.0   6.0  0.0  0.0  
1794  0.0  0.0  2.0   9.0  13.0   6.0  0.0  0.0  
1795  0.0  0.0  5.0  12.0  16.0  12.0  0.0  0.0  
1796  0.0  1.0  8.0  12.0  14.0  12.0  1.0  0.0  

[1797 rows x 64 columns]

In [7]:
p['target']=d.target
p

0    1     2     3     4     5    6    7    8    9  ...   55   56  \
0     0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  0.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
1793  0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  0.0  0.0   
1794  0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1796  0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  0.0  0.0   

       57   58    59    60    61   62   63  target  
0     0.0  6.0  13.0  10.0   0.0  0.0  0.0       0  
1     0.0  0.0  11.0  16.0  10.0  0.0  0.0       1  
2     0.0  0.0   3.0  11.0  16.0  9.0  0.0       2  
3     0.0  7.0  13.0  13.0   9.0  0.0  0.0       3  
4     0.0  0.0   2.0  16.0   4.0  0.0  0.0       4  
...   ...  ...   ...   ...   ...  ...  ...     ...  
1792  0.0  2.0  14.0  15.0   9.0  0.0  0.0       9  
1793  0.0  6.0  16.0  14.0   6.0  0.0  0.0       0  
1794  0.0  2.0   9.0  13.0   6.0  0.0  0.0       8  
1795  0.0  5.0  12.0  16.0  12.0  0.0  0.0       9  
1796  1.0  8.0  12.0  14.0  12.0  1.0  0.0       8  

[1797 rows x 65 columns]

In [8]:
from sklearn.model_selection import train_test_split


In [9]:
x_train,x_test,y_train,y_test=train_test_split(p.drop(['target'],axis='columns'),p['target'],test_size=0.2)

In [10]:
x_train

0    1     2     3     4     5    6    7    8    9   ...    54   55  \
405   0.0  0.0   5.0  16.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  11.0  0.0   
110   0.0  0.0   0.0  10.0  15.0   0.0  0.0  0.0  0.0  0.0  ...   0.0  0.0   
177   0.0  0.0   0.0   0.0  12.0  11.0  1.0  0.0  0.0  0.0  ...   1.0  0.0   
764   0.0  0.0   4.0  15.0  16.0  11.0  0.0  0.0  0.0  0.0  ...   0.0  0.0   
30    0.0  0.0  10.0  14.0  11.0   3.0  0.0  0.0  0.0  4.0  ...   0.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...   ...  ...   
1609  0.0  0.0   0.0   6.0  12.0   0.0  0.0  0.0  0.0  0.0  ...   5.0  0.0   
107   0.0  0.0   0.0   0.0   6.0  10.0  0.0  0.0  0.0  0.0  ...   0.0  0.0   
899   0.0  0.0   6.0  14.0  16.0   5.0  0.0  0.0  0.0  2.0  ...   3.0  0.0   
19    0.0  0.0   6.0  14.0   4.0   0.0  0.0  0.0  0.0  0.0  ...  16.0  2.0   
208   0.0  0.0   2.0  12.0  12.0   2.0  0.0  0.0  0.0  0.0  ...   2.0  0.0   

       56   57    58    59    60    61    62   63  
405   0.0  0.0   5.0  11.0  12.0  14.0   3.0  0.0  
110   0.0  0.0   0.0  12.0   9.0   0.0   0.0  0.0  
177   0.0  0.0   0.0   0.0  11.0  12.0   0.0  0.0  
764   0.0  0.0   6.0  11.0   0.0   0.0   0.0  0.0  
30    0.0  0.0  11.0  16.0  12.0   3.0   0.0  0.0  
...   ...  ...   ...   ...   ...   ...   ...  ...  
1609  0.0  0.0   0.0   6.0  15.0  12.0   1.0  0.0  
107   0.0  0.0   0.0   0.0   8.0  15.0   0.0  0.0  
899   0.0  0.0   3.0  14.0  16.0   6.0   0.0  0.0  
19    0.0  0.0   7.0  16.0  16.0  13.0  11.0  1.0  
208   0.0  0.0   3.0  13.0  12.0   3.0   0.0  0.0  

[1437 rows x 64 columns]

In [11]:
lg=LogisticRegression()
lg.fit(x_train,y_train)
lg.score(x_test,y_test)

C:\Users\Windows\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9694444444444444

In [12]:
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
dt.score(x_test,y_test)

0.8805555555555555

In [13]:
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9805555555555555

In [14]:
sv=SVC()
sv.fit(x_train,y_train)
sv.score(x_test,y_test)

0.9861111111111112

In [15]:
def getscore(model,xtrain,ytrain,xtest,ytest):
    model.fit(xtrain,ytrain)
    print(model.score(xtest,ytest))

In [16]:
getscore(DecisionTreeClassifier(),x_train,y_train,x_test,y_test)

0.8722222222222222


In [17]:
getscore(SVC(),x_train,y_train,x_test,y_test)

0.9861111111111112


In [18]:
getscore(RandomForestClassifier(),x_train,y_train,x_test,y_test)

0.9777777777777777


In [19]:
from sklearn.model_selection import KFold
k=KFold(n_splits=3)

In [20]:
for train_index,test_index in k.split(['tom',1,'marry',2,20,15,18,'student',18]):
    print(train_index,test_index)


[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [21]:
scores_logistic = []
scores_svm = []
scores_rf = []

In [22]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)


for train_index, test_index in folds.split(d.data,d.target):
    X_train, X_test, y_train, y_test = d.data[train_index], d.data[test_index], d.target[train_index], d.target[test_index]
   
    
    
    scores_logistic.append(getscore(LogisticRegression(), X_train, y_train,X_test, y_test))  
    scores_svm.append(getscore(SVC(),X_train, y_train,X_test, y_test))
    scores_rf.append(getscore(RandomForestClassifier(n_estimators=40), X_train, y_train,X_test, y_test))
print(scores_logistic)
print(scores_svm)
print(scores_rf)


C:\Users\Windows\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9215358931552587
0.9649415692821369
0.9165275459098498


C:\Users\Windows\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9415692821368948
0.9799666110183639
0.9432387312186978


C:\Users\Windows\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9165275459098498
0.9649415692821369
0.9131886477462438
[None, None, None]
[None, None, None]
[None, None, None]


In [23]:
from sklearn.model_selection import cross_val_score

In [24]:
logscore=cross_val_score(LogisticRegression(),d.data,d.target)

C:\Users\Windows\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Windows\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_i

In [25]:
np.average(logscore)

0.9137650882079852

In [26]:
rfscore=cross_val_score(RandomForestClassifier(n_estimators=5),d.data,d.target)

In [27]:

np.average(rfscore)

0.8614639430516868

In [28]:
rfscore=cross_val_score(RandomForestClassifier(n_estimators=10),d.data,d.target)

In [29]:
np.average(rfscore)

0.8976508820798514

In [30]:
rfscore=cross_val_score(RandomForestClassifier(n_estimators=20),d.data,d.target)

In [31]:
np.average(rfscore)

0.9254580625193439

In [32]:
rfscore=cross_val_score(RandomForestClassifier(n_estimators=30),d.data,d.target)

In [33]:
np.average(rfscore)

0.9204394924172081

In [34]:
rfscore=cross_val_score(RandomForestClassifier(n_estimators=50),d.data,d.target)

In [35]:
np.average(rfscore)

0.9360198081089447